allprojects {
    repositories {
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://maven.aliyun.com/repository/jcenter' }
        maven { url 'https://download.flutter.io' }
        maven { url 'https://storage.googleapis.com/download.flutter.io' }
        google()
        mavenCentral()
    }
}

subprojects { subproject ->
    afterEvaluate {
        if (subproject.hasProperty('android')) {
            subproject.android {
                if (subproject.android.compileSdkVersion == null) {
                    compileSdkVersion 34
                }
            }
        }
    }
    subproject.configurations.all {
        resolutionStrategy {
            eachDependency { details ->
                if (details.requested.group == 'com.android.tools.build' && details.requested.name == 'gradle') {
                    details.useVersion '7.3.0'
                }
            }
        }
    }
}
